package ghostInter.controlToBe;

import java.util.HashMap;
import java.util.Map;

class ExerciseToBe
{
    private Map<Integer, String> appToBefileEn = new HashMap<>();
    private Map<Integer, String> appToBefileRu = new HashMap<>();

    Map<Integer, String> getAppToBefileEn() {
        getStrEn();
        return appToBefileEn;
    }
    Map<Integer, String> getAppToBefileRu() {
        getStrRu();
        return appToBefileRu;
    }

    private Map<Integer, String> getStrEn(){
        Runnable runnable = () -> {
            Runnable runnable1 = () -> {
                appToBefileEn.put(0,"It's interesting");
                appToBefileEn.put(1,"I'm at home");
                appToBefileEn.put(2,"We're at home");
                appToBefileEn.put(3,"You're at home");
                appToBefileEn.put(4,"They're at home");
                appToBefileEn.put(5,"He's at home");
                appToBefileEn.put(6,"I'm happy");
                appToBefileEn.put(7,"You're right");
                appToBefileEn.put(8,"They're at work");
                appToBefileEn.put(9,"He's at school");
                appToBefileEn.put(10,"She's here");
                appToBefileEn.put(11,"It's there");
                appToBefileEn.put(12,"I'm sure");
                appToBefileEn.put(13,"We're in the park");
                appToBefileEn.put(14,"We're so happy");
                appToBefileEn.put(15,"We're friends");
                appToBefileEn.put(16,"He's right");
                appToBefileEn.put(17,"You're very kind");
                appToBefileEn.put(18,"You're a good person");
                appToBefileEn.put(19,"They're our friends");
                appToBefileEn.put(20,"They're rich");
                appToBefileEn.put(21,"They're poor");
                appToBefileEn.put(22,"They're lazy");
                appToBefileEn.put(23,"He's a doctor");
                appToBefileEn.put(24,"He's a manager");
                appToBefileEn.put(25,"He's my friend");
                appToBefileEn.put(26,"He's my boyfriend");
                appToBefileEn.put(27,"He's a businessman");
                appToBefileEn.put(28,"She's a teacher");
                appToBefileEn.put(29,"She's my girlfriend");
            };
            runnable1.run();
            Runnable runnable2 = () -> {
                appToBefileEn.put(30,"She's my teacher");
                appToBefileEn.put(31,"She's a student");
                appToBefileEn.put(32,"He's her husband");
                appToBefileEn.put(33,"She's his wife");
                appToBefileEn.put(34,"It's important");
                appToBefileEn.put(35,"It's very important");
                appToBefileEn.put(36,"It's so important");
                appToBefileEn.put(37,"It's difficult");
                appToBefileEn.put(38,"It's so difficult");
                appToBefileEn.put(39,"It's easy");
                appToBefileEn.put(40,"It's very easy");
                appToBefileEn.put(41,"It's good");
                appToBefileEn.put(42,"It's so bad");
                appToBefileEn.put(43,"It's a good result");
                appToBefileEn.put(44,"It's a very good result");
                appToBefileEn.put(45,"It's an interesting idea");
                appToBefileEn.put(46,"It's a very interesting idea");
                appToBefileEn.put(47,"It's a useful lesson");
                appToBefileEn.put(48,"It's a very useful lesson");
                appToBefileEn.put(49,"It's an easy lesson");
                appToBefileEn.put(50,"It's a very easy lesson");
                appToBefileEn.put(51,"It's a big success");
                appToBefileEn.put(52,"It's a very big success");
                appToBefileEn.put(53,"It's a high level");
                appToBefileEn.put(54,"It's a very high level");
                appToBefileEn.put(55,"It's a low level");
                appToBefileEn.put(56,"It's a very low level");
                appToBefileEn.put(57,"It's an important detail");
                appToBefileEn.put(58,"It's an informative lesson");
                appToBefileEn.put(59,"It's a very informative lesson");
            };
            runnable2.run();
            Runnable runnable3 = () -> {
                appToBefileEn.put(60,"It's a big mistake");
                appToBefileEn.put(61,"It's a very big mistake");
                appToBefileEn.put(62,"It's a small mistake");
                appToBefileEn.put(63,"It's a very small mistake");
                appToBefileEn.put(64,"It's a very important detail");
                appToBefileEn.put(65,"It's a brilliant result");
                appToBefileEn.put(66,"It's the best channel");
                appToBefileEn.put(67,"You're the best teacher");
                appToBefileEn.put(68,"You're the best teacher in the world");
                appToBefileEn.put(69,"It's the best example");
                appToBefileEn.put(70,"It's so boring");
                appToBefileEn.put(71,"It's very boring");
                appToBefileEn.put(72,"It's too boring");
                appToBefileEn.put(73,"It's too easy");
                appToBefileEn.put(74,"It's too difficult");
                appToBefileEn.put(75,"It's too expensive");
                appToBefileEn.put(76,"It's cheap");
                appToBefileEn.put(77,"It's the best course");
                appToBefileEn.put(78,"It's cold!");
                appToBefileEn.put(79,"It's warm!");
                appToBefileEn.put(80,"It's hot!");
                appToBefileEn.put(81,"It's rainy!");
                appToBefileEn.put(82,"It's sunny!");
                appToBefileEn.put(83,"It's dark!");
                appToBefileEn.put(84,"It's a cold day");
                appToBefileEn.put(85,"It's a warm day");
                appToBefileEn.put(86,"It's a hot day");
                appToBefileEn.put(87,"It's too hot");
                appToBefileEn.put(88,"It's too cold");
                appToBefileEn.put(89,"It's obvious");
            };
            runnable3.run();
            Runnable runnable4 = () -> {
                appToBefileEn.put(90,"She's a very beautiful girl");
                appToBefileEn.put(91,"It's simple");
                appToBefileEn.put(92,"It's possible");
                appToBefileEn.put(93,"It's impossible");
                appToBefileEn.put(94,"I'm ready");
                appToBefileEn.put(95,"It's on the right");
                appToBefileEn.put(96,"It's on the left");
                appToBefileEn.put(97,"I'm fine");
                appToBefileEn.put(98,"It's better");
                appToBefileEn.put(99,"It's worse");
                appToBefileEn.put(100,"He's a young man");
                appToBefileEn.put(101,"It's such an interesting story");
                appToBefileEn.put(102,"It's such an important meeting");
                appToBefileEn.put(103,"It's so popular");
                appToBefileEn.put(104,"It's such a popular song");
                appToBefileEn.put(105,"It's such a difficult exam");
                appToBefileEn.put(106,"It's such an easy test");
                appToBefileEn.put(107,"He's a professional teacher");
                appToBefileEn.put(108,"He's such a professional teacher");
                appToBefileEn.put(109,"It's an expensive car");
                appToBefileEn.put(110,"It's such an expensive car");
                appToBefileEn.put(111,"She's beautiful");
                appToBefileEn.put(112,"She's so beautiful");
                appToBefileEn.put(113,"She's very beautiful");
                appToBefileEn.put(114,"She's a beautiful girl");
                appToBefileEn.put(115,"She's such a beautiful girl");
                appToBefileEn.put(116,"It's an easy exercise");
                appToBefileEn.put(117,"It's such an easy exercise");
                appToBefileEn.put(118,"It's so useful");
                appToBefileEn.put(119,"It's such a useful video");
            };
            runnable4.run();
            Runnable runnable5 = () -> {
                appToBefileEn.put(120,"It's such a bad situation");
                appToBefileEn.put(121,"It's so cheap");
                appToBefileEn.put(122,"It's such a cheap thing");
                appToBefileEn.put(123,"He's so strange");
                appToBefileEn.put(124,"He's such a strange person");
                appToBefileEn.put(125,"He's so clever");
                appToBefileEn.put(126,"He's such a clever man");
                appToBefileEn.put(127,"He's talented");
                appToBefileEn.put(128,"He's such a talented boy");
                appToBefileEn.put(129,"He's such a poor boy");
                appToBefileEn.put(130,"It's so effective");
                appToBefileEn.put(131,"It's such an effective method");
                appToBefileEn.put(132,"She's such a smart girl");
                appToBefileEn.put(133,"She's so kind");
                appToBefileEn.put(134,"She's such a kind woman");
                appToBefileEn.put(135,"She's such a wise woman");
                appToBefileEn.put(136,"It's such a simple answer");
                appToBefileEn.put(137,"My friend is at home");
                appToBefileEn.put(138,"My mother is at work");
                appToBefileEn.put(139,"Their idea is very interesting");
                appToBefileEn.put(140,"This lesson is very useful");
                appToBefileEn.put(141,"These lessons are very useful");
                appToBefileEn.put(142,"This year is very difficult");
                appToBefileEn.put(143,"This video is very informative");
                appToBefileEn.put(144,"These videos are very informative");
                appToBefileEn.put(145,"All these videos are very useful");
                appToBefileEn.put(146,"All your videos are so interesting");
                appToBefileEn.put(147,"This student is so hard-working");
                appToBefileEn.put(148,"These students are very lazy");
                appToBefileEn.put(149,"My boss is very busy now");
            };
            runnable5.run();
            Runnable runnable6 = () -> {
                appToBefileEn.put(150,"Her boss is very busy at the moment");
                appToBefileEn.put(151,"I have a computer! The computer is new!");
                appToBefileEn.put(152,"I have a car! The car is very good!");
                appToBefileEn.put(153,"This boy is very clever");
                appToBefileEn.put(154,"The boy is very clever");
                appToBefileEn.put(155,"The exam is difficult");
                appToBefileEn.put(156,"The test is easy");
                appToBefileEn.put(157,"The lesson is useful");
                appToBefileEn.put(158,"The lesson is interesting");
                appToBefileEn.put(159,"The rule is very important");
                appToBefileEn.put(160,"This man is a doctor");
                appToBefileEn.put(161,"These men are managers");
                appToBefileEn.put(162,"That woman is a designer");
                appToBefileEn.put(163,"Those women are teachers");
                appToBefileEn.put(164,"These lessons are so effective");
                appToBefileEn.put(165,"Those lessons are ineffective");
                appToBefileEn.put(166,"This problem is very big");
                appToBefileEn.put(167,"These problems are small");
                appToBefileEn.put(168,"These lessons are really good");
                appToBefileEn.put(169,"This information is really useful");
                appToBefileEn.put(170,"This thing is very important");
                appToBefileEn.put(171,"These things are very important");
                appToBefileEn.put(172,"Time is money");
                appToBefileEn.put(173,"Money is important");
                appToBefileEn.put(174,"English is easy");
                appToBefileEn.put(175,"Chinese is very difficult");
                appToBefileEn.put(176,"Love is a wonderful feeling");
                appToBefileEn.put(177,"Knowledge is power");
                appToBefileEn.put(178,"This place is very beautiful");
                appToBefileEn.put(179,"This company is very rich");
                appToBefileEn.put(180,"I'm Russia");
                appToBefileEn.put(181,"He's American");
                appToBefileEn.put(182,"I'm twenty");
                appToBefileEn.put(183,"She's thirty");
                appToBefileEn.put(184,"My mother is a doctor! She's forty");
                appToBefileEn.put(185,"I'm twenty-one");
                appToBefileEn.put(186,"My brother is 21");
                appToBefileEn.put(187,"His wife is 32");
            };
            runnable6.run();
        };
        runnable.run();
        return appToBefileEn;
    }
    private Map<Integer, String> getStrRu(){
        Runnable runnable = () -> {
            Runnable runnable1 = () -> {
                appToBefileRu.put(0,"Это интересно");
                appToBefileRu.put(1,"Я дома");
                appToBefileRu.put(2,"Мы дома");
                appToBefileRu.put(3,"Ты дома");
                appToBefileRu.put(4,"Они дома");
                appToBefileRu.put(5,"Он дома");
                appToBefileRu.put(6,"Я счастлив");
                appToBefileRu.put(7,"Ты прав");
                appToBefileRu.put(8,"Они на работе");
                appToBefileRu.put(9,"Он в школе");
                appToBefileRu.put(10,"Она сдесь");
                appToBefileRu.put(11,"Это там");
                appToBefileRu.put(12,"Я уверен");
                appToBefileRu.put(13,"Мы в парке");
                appToBefileRu.put(14,"Мы так счастливы");
                appToBefileRu.put(15,"Мы друзья");
                appToBefileRu.put(16,"Он прав");
                appToBefileRu.put(17,"Ты очень добрый");
                appToBefileRu.put(18,"Ты хороший человек");
                appToBefileRu.put(19,"Они наши друзья");
                appToBefileRu.put(20,"Они богатые");
                appToBefileRu.put(21,"Они бедные");
                appToBefileRu.put(22,"Они ленивые");
                appToBefileRu.put(23,"Он врач");
                appToBefileRu.put(24,"Он менеджер");
                appToBefileRu.put(25,"Он мой друг");
                appToBefileRu.put(26,"Он мой парень");
                appToBefileRu.put(27,"Он бизнесмен");
                appToBefileRu.put(28,"Она учительница");
                appToBefileRu.put(29,"Она моя девушка");
            };
            runnable1.run();
            Runnable runnable2 = () -> {
                appToBefileRu.put(30,"Она моя учительница");
                appToBefileRu.put(31,"Она студентка");
                appToBefileRu.put(32,"Он её муж");
                appToBefileRu.put(33,"Она его жена");
                appToBefileRu.put(34,"Это важно");
                appToBefileRu.put(35,"Это очень важно");
                appToBefileRu.put(36,"Это так важно");
                appToBefileRu.put(37,"Это сложно");
                appToBefileRu.put(38,"Это так сложно");
                appToBefileRu.put(39,"Это легко");
                appToBefileRu.put(40,"Это очень легко");
                appToBefileRu.put(41,"Это хорошо");
                appToBefileRu.put(42,"Это так плохо");
                appToBefileRu.put(43,"Это хороший результат");
                appToBefileRu.put(44,"Это очень хороший результат");
                appToBefileRu.put(45,"Это интересная идея");
                appToBefileRu.put(46,"Это очень интересная идея");
                appToBefileRu.put(47,"Это полезный урок");
                appToBefileRu.put(48,"Это очень полезный урок");
                appToBefileRu.put(49,"Это легкий урок");
                appToBefileRu.put(50,"Это очень легий урок");
                appToBefileRu.put(51,"Это большой упех");
                appToBefileRu.put(52,"Это очень большой успех");
                appToBefileRu.put(53,"Это высокий уровень");
                appToBefileRu.put(54,"Это очень высокий уровень");
                appToBefileRu.put(55,"Это низкий уровень");
                appToBefileRu.put(56,"Это очень низкий уровень");
                appToBefileRu.put(57,"Это важная деталь");
                appToBefileRu.put(58,"Это информативный урок");
                appToBefileRu.put(59,"Это очень информативный урок");
            };
            runnable2.run();
            Runnable runnable3 = () -> {
                appToBefileRu.put(60,"Это большая ошибка");
                appToBefileRu.put(61,"Это очень большая ошибка");
                appToBefileRu.put(62,"Это маленькая ошибка");
                appToBefileRu.put(63,"Это очень маленькая ошибка");
                appToBefileRu.put(64,"Это очень важная деталь");
                appToBefileRu.put(65,"Это блестящий результат");
                appToBefileRu.put(66,"Это лучший канал");
                appToBefileRu.put(67,"Ты лучший учитель");
                appToBefileRu.put(68,"Ты лучший учитель в мире");
                appToBefileRu.put(69,"Это лучший пример");
                appToBefileRu.put(70,"Это так скучно");
                appToBefileRu.put(71,"Это очень скучно");
                appToBefileRu.put(72,"Это слишком скучно");
                appToBefileRu.put(73,"Это слишком легко");
                appToBefileRu.put(74,"Это слишком сложно");
                appToBefileRu.put(75,"Это слишком дорого");
                appToBefileRu.put(76,"Это дешево");
                appToBefileRu.put(77,"Это самый лучший курс");
                appToBefileRu.put(78,"Холодно!");
                appToBefileRu.put(79,"Тепло!");
                appToBefileRu.put(80,"Жарко!");
                appToBefileRu.put(81,"Дождливо!");
                appToBefileRu.put(82,"Солнечно!");
                appToBefileRu.put(83,"Темно!");
                appToBefileRu.put(84,"Это холодный день");
                appToBefileRu.put(85,"Это теплый день");
                appToBefileRu.put(86,"Это жаркий день");
                appToBefileRu.put(87,"Слишком жарко");
                appToBefileRu.put(88,"Слишком холодно");
                appToBefileRu.put(89,"Это очевидно");
            };
            runnable3.run();
            Runnable runnable4 = () -> {
                appToBefileRu.put(90,"Она очень красивая девушка");
                appToBefileRu.put(91,"Это просто");
                appToBefileRu.put(92,"Это возможно");
                appToBefileRu.put(93,"Это не возможно");
                appToBefileRu.put(94,"Я готов");
                appToBefileRu.put(95,"Это справа");
                appToBefileRu.put(96,"Это слева");
                appToBefileRu.put(97,"Я в порядке");
                appToBefileRu.put(98,"Это лучше");
                appToBefileRu.put(99,"Это хуже");
                appToBefileRu.put(100,"Он молодой человек");
                appToBefileRu.put(101,"Это такая интересная история");
                appToBefileRu.put(102,"Это такая важная встреча");
                appToBefileRu.put(103,"Это так популярно");
                appToBefileRu.put(104,"Это такая популярная песня");
                appToBefileRu.put(105,"Это такой сложный экзамен");
                appToBefileRu.put(106,"Это такой легкий тест");
                appToBefileRu.put(107,"Он професиональный учитель");
                appToBefileRu.put(108,"Он такой профессиональный учитель");
                appToBefileRu.put(109,"Это дорогая машина");
                appToBefileRu.put(110,"Это такая дорогая машина");
                appToBefileRu.put(111,"Она красивая");
                appToBefileRu.put(112,"Она такая красивая");
                appToBefileRu.put(113,"Она очень красивая");
                appToBefileRu.put(114,"Она красивая девушка");
                appToBefileRu.put(115,"Она такая красивая девушка");
                appToBefileRu.put(116,"Это легкое упражнение");
                appToBefileRu.put(117,"Это такое легкое упражнение");
                appToBefileRu.put(118,"Это так полезно");
                appToBefileRu.put(119,"Это такое полезно видео");
            };
            runnable4.run();
            Runnable runnable5 = () -> {
                appToBefileRu.put(120,"Это такая плохая ситуация");
                appToBefileRu.put(121,"Это так дешево");
                appToBefileRu.put(122,"Это такая дешевая вещь");
                appToBefileRu.put(123,"Он такой странный");
                appToBefileRu.put(124,"Он такой странный человек");
                appToBefileRu.put(125,"Он такой умный");
                appToBefileRu.put(126,"Он такой умный мужчина");
                appToBefileRu.put(127,"Он талантливый");
                appToBefileRu.put(128,"Он такой талантливый мальчик");
                appToBefileRu.put(129,"Он такой бедный мальчик");
                appToBefileRu.put(130,"Это так эффективно");
                appToBefileRu.put(131,"Это такой эффективный метод");
                appToBefileRu.put(132,"Она такая смышленая девочка");
                appToBefileRu.put(133,"Она такая добрая");
                appToBefileRu.put(134,"Она такая добрая женщина");
                appToBefileRu.put(135,"Она такая мудрая женщина");
                appToBefileRu.put(136,"Это такой простой ответ");
                appToBefileRu.put(137,"Мой друг дома");
                appToBefileRu.put(138,"Моя мама на работе");
                appToBefileRu.put(139,"Их идея очень интересная");
                appToBefileRu.put(140,"Этот урок очень полезный");
                appToBefileRu.put(141,"Эти уроки очень полезные");
                appToBefileRu.put(142,"Этот год очень сложный");
                appToBefileRu.put(143,"Это видео очень информативное");
                appToBefileRu.put(144,"Эти видео очень информативные");
                appToBefileRu.put(145,"Все эти видео очень полезные");
                appToBefileRu.put(146,"Все твои видео такие интересные");
                appToBefileRu.put(147,"Этот студент такой трудолюбивый");
                appToBefileRu.put(148,"Эти суденты очень ленивые");
                appToBefileRu.put(149,"Мой босс очень занят сейчас");
            };
            runnable5.run();
            Runnable runnable6 = () -> {
                appToBefileRu.put(150,"Её босс очень занят в настоящий момент");
                appToBefileRu.put(151,"У меня есть компьютер! Компьютер новый!");
                appToBefileRu.put(152,"У меня есть машина! Машина очень хорошая!");
                appToBefileRu.put(153,"Этот мальчик очень умный ");
                appToBefileRu.put(154,"Мальчик очень умный");
                appToBefileRu.put(155,"Экзамен сложный");
                appToBefileRu.put(156,"Тест легкий");
                appToBefileRu.put(157,"Урок полезный");
                appToBefileRu.put(158,"Урок интересный");
                appToBefileRu.put(159,"Правило очень важное");
                appToBefileRu.put(160,"Этот мужчина врач");
                appToBefileRu.put(161,"Эти мужчины менеджеры");
                appToBefileRu.put(162,"Та женщина дизайнер");
                appToBefileRu.put(163,"Те женщины учителя");
                appToBefileRu.put(164,"Эти уроки такие эффективные");
                appToBefileRu.put(165,"Те уроки не эффективные");
                appToBefileRu.put(166,"Эта проблема очень большая");
                appToBefileRu.put(167,"Эти проблемы маленькие");
                appToBefileRu.put(168,"Эти уроки реально хорошие");
                appToBefileRu.put(169,"Эта информация реально полезная");
                appToBefileRu.put(170,"Эта вещь очень важная");
                appToBefileRu.put(171,"Эти вещи очень важные");
                appToBefileRu.put(172,"Время деньги");
                appToBefileRu.put(173,"Деньги важны");
                appToBefileRu.put(174,"Английский легкий");
                appToBefileRu.put(175,"Китайский очень сложный");
                appToBefileRu.put(176,"Любовь прекрасное чувство");
                appToBefileRu.put(177,"Знание сила");
                appToBefileRu.put(178,"Это место очень красивое");
                appToBefileRu.put(179,"Эта компания очень богатая");
                appToBefileRu.put(180,"Я русский");
                appToBefileRu.put(181,"Он американец");
                appToBefileRu.put(182,"Мне 20");
                appToBefileRu.put(183,"Ей 30");
                appToBefileRu.put(184,"Моя мама врач! Ей 40");
                appToBefileRu.put(185,"Мне 21");
                appToBefileRu.put(186,"Моему брату 21");
                appToBefileRu.put(187,"Его жене 32");
            };
            runnable6.run();
        };
        runnable.run();
        return appToBefileRu;
    }
}