package english.ps.approvals;

import english.panelsAndNumber.IRoot;
import english.panelsAndNumber.NumbersAppPS;
import javafx.geometry.HPos;
import javafx.geometry.Insets;
import javafx.scene.layout.ColumnConstraints;
import javafx.scene.layout.GridPane;

public class MethodEng implements IRoot
{
    private LabEn labEn = new LabEn();
    private NumbersAppPS numbersAppPS = new NumbersAppPS();
    private final int e = 4;
    private final int f = 5;

    public void getEnglishListAppPS(){
        englishListAppPs.setPageFactory(this::indexLabelAppPS);
        englishListAppPs.setLayoutX(20);
        englishListAppPs.setLayoutY(60);
        englishListAppPs.setPrefSize(1360, 800);
    }

//////////////////////

    private GridPane indexLabelAppPS(Integer str) {

        GridPane enPanel = new GridPane();
        enPanel.setLayoutX(0);
        enPanel.setLayoutY(0);
        enPanel.setPadding(new Insets(30));

//        enPanel.setGridLinesVisible(true);
//        enPanel.setStyle("-fx-border-color: RED;");

        enPanel.setHgap(10);
        enPanel.setVgap(5);
        ColumnConstraints c1 = new ColumnConstraints();
        ColumnConstraints c2 = new ColumnConstraints();
        ColumnConstraints c3 = new ColumnConstraints();
        ColumnConstraints c4 = new ColumnConstraints();
        ColumnConstraints c5 = new ColumnConstraints();
        ColumnConstraints c6 = new ColumnConstraints();
        c1.setPercentWidth(5);
        c2.setHalignment(HPos.CENTER);
        c2.setPercentWidth(10);
        c3.setPercentWidth(100);
        c4.setPercentWidth(5);
        c5.setHalignment(HPos.CENTER);
        c5.setPercentWidth(10);
        c6.setPercentWidth(100);
        enPanel.getColumnConstraints().addAll(c1, c2, c3, c4, c5, c6);

        int numberLeft = 1;
        int numberRight = 4;
        int textLeft = 2;
        int textRight = 5;

        if (str.byteValue()==0) {

            enPanel.add(numbersAppPS.getN1(), numberLeft, 0);
            enPanel.add(numbersAppPS.getN2(), numberLeft, 1);
            enPanel.add(numbersAppPS.getN3(), numberLeft, 2);
            enPanel.add(numbersAppPS.getN4(), numberLeft, 3);
            enPanel.add(numbersAppPS.getN5(), numberLeft, 4);
            enPanel.add(numbersAppPS.getN6(), numberLeft, 5);
            enPanel.add(numbersAppPS.getN7(), numberLeft, 6);
            enPanel.add(numbersAppPS.getN8(), numberLeft, 7);
            enPanel.add(numbersAppPS.getN9(), numberLeft, 8);
            enPanel.add(numbersAppPS.getN10(), numberLeft, 9);
            enPanel.add(numbersAppPS.getN11(), numberLeft, 10);
            enPanel.add(numbersAppPS.getN12(), numberLeft, 11);
            enPanel.add(numbersAppPS.getN13(), numberLeft, 12);
            enPanel.add(numbersAppPS.getN14(), numberLeft, 13);
            enPanel.add(numbersAppPS.getN15(), numberLeft, 14);
            enPanel.add(numbersAppPS.getN16(), numberLeft, 15);
            enPanel.add(numbersAppPS.getN17(), numberLeft, 16);
            enPanel.add(numbersAppPS.getN18(), numberLeft, 17);
            enPanel.add(numbersAppPS.getN19(), numberLeft, 18);
            enPanel.add(numbersAppPS.getN20(), numberRight, 0);
            enPanel.add(numbersAppPS.getN21(), numberRight, 1);
            enPanel.add(numbersAppPS.getN22(), numberRight, 2);
            enPanel.add(numbersAppPS.getN23(), numberRight, 3);
            enPanel.add(numbersAppPS.getN24(), numberRight, 4);
            enPanel.add(numbersAppPS.getN25(), numberRight, 5);
            enPanel.add(numbersAppPS.getN26(), numberRight, 6);
            enPanel.add(numbersAppPS.getN27(), numberRight, 7);
            enPanel.add(numbersAppPS.getN28(), numberRight, 8);
            enPanel.add(numbersAppPS.getN29(), numberRight, 9);
            enPanel.add(numbersAppPS.getN30(), numberRight, 10);
            enPanel.add(numbersAppPS.getN31(), numberRight, 11);
            enPanel.add(numbersAppPS.getN32(), numberRight, 12);
            enPanel.add(numbersAppPS.getN33(), numberRight, 13);
            enPanel.add(numbersAppPS.getN34(), numberRight, 14);
            enPanel.add(numbersAppPS.getN35(), numberRight, 15);
            enPanel.add(numbersAppPS.getN36(), numberRight, 16);
            enPanel.add(numbersAppPS.getN37(), numberRight, 17);
            enPanel.add(numbersAppPS.getN38(), numberRight, 18);

            enPanel.add(labEn.getLabEn1(), textLeft, 0);
            enPanel.add(labEn.getLabEn2(), textLeft, 1);
            enPanel.add(labEn.getLabEn3(), textLeft, 2);
            enPanel.add(labEn.getLabEn4(), textLeft, 3);
            enPanel.add(labEn.getLabEn5(), textLeft, 4);
            enPanel.add(labEn.getLabEn6(), textLeft, 5);
            enPanel.add(labEn.getLabEn7(), textLeft, 6);
            enPanel.add(labEn.getLabEn8(), textLeft, 7);
            enPanel.add(labEn.getLabEn9(), textLeft, 8);
            enPanel.add(labEn.getLabEn10(), textLeft, 9);
            enPanel.add(labEn.getLabEn11(), textLeft, 10);
            enPanel.add(labEn.getLabEn12(), textLeft, 11);
            enPanel.add(labEn.getLabEn13(), textLeft, 12);
            enPanel.add(labEn.getLabEn14(), textLeft, 13);
            enPanel.add(labEn.getLabEn15(), textLeft, 14);
            enPanel.add(labEn.getLabEn16(), textLeft, 15);
            enPanel.add(labEn.getLabEn17(), textLeft, 16);
            enPanel.add(labEn.getLabEn18(), textLeft, 17);
            enPanel.add(labEn.getLabEn19(), textLeft, 18);
            enPanel.add(labEn.getLabEn20(), textRight, 0);
            enPanel.add(labEn.getLabEn21(), textRight, 1);
            enPanel.add(labEn.getLabEn22(), textRight, 2);
            enPanel.add(labEn.getLabEn23(), textRight, 3);
            enPanel.add(labEn.getLabEn24(), textRight, 4);
            enPanel.add(labEn.getLabEn25(), textRight, 5);
            enPanel.add(labEn.getLabEn26(), textRight, 6);
            enPanel.add(labEn.getLabEn27(), textRight, 7);
            enPanel.add(labEn.getLabEn28(), textRight, 8);
            enPanel.add(labEn.getLabEn29(), textRight, 9);
            enPanel.add(labEn.getLabEn30(), textRight, 10);
            enPanel.add(labEn.getLabEn31(), textRight, 11);
            enPanel.add(labEn.getLabEn32(), textRight, 12);
            enPanel.add(labEn.getLabEn33(), textRight, 13);
            enPanel.add(labEn.getLabEn34(), textRight, 14);
            enPanel.add(labEn.getLabEn35(), textRight, 15);
            enPanel.add(labEn.getLabEn36(), textRight, 16);
            enPanel.add(labEn.getLabEn37(), textRight, 17);
            enPanel.add(labEn.getLabEn38(), textRight, 18);


        } else if (str.byteValue() == 1){

            enPanel.add(numbersAppPS.getN39(), numberLeft, 0);
            enPanel.add(numbersAppPS.getN40(), numberLeft, 1);
            enPanel.add(numbersAppPS.getN41(), numberLeft, 2);
            enPanel.add(numbersAppPS.getN42(), numberLeft, 3);
            enPanel.add(numbersAppPS.getN43(), numberLeft, 4);
            enPanel.add(numbersAppPS.getN44(), numberLeft, 5);
            enPanel.add(numbersAppPS.getN45(), numberLeft, 6);
            enPanel.add(numbersAppPS.getN46(), numberLeft, 7);
            enPanel.add(numbersAppPS.getN47(), numberLeft, 8);
            enPanel.add(numbersAppPS.getN48(), numberLeft, 9);
            enPanel.add(numbersAppPS.getN49(), numberLeft, 10);
            enPanel.add(numbersAppPS.getN50(), numberLeft, 11);
            enPanel.add(numbersAppPS.getN51(), numberLeft, 12);
            enPanel.add(numbersAppPS.getN52(), numberLeft, 13);
            enPanel.add(numbersAppPS.getN53(), numberLeft, 14);
            enPanel.add(numbersAppPS.getN54(), numberLeft, 15);
            enPanel.add(numbersAppPS.getN55(), numberLeft, 16);
            enPanel.add(numbersAppPS.getN56(), numberLeft, 17);
            enPanel.add(numbersAppPS.getN57(), numberLeft, 18);
            enPanel.add(numbersAppPS.getN58(), numberRight, 0);
            enPanel.add(numbersAppPS.getN59(), numberRight, 1);
            enPanel.add(numbersAppPS.getN60(), numberRight, 2);
            enPanel.add(numbersAppPS.getN61(), numberRight, 3);
            enPanel.add(numbersAppPS.getN62(), numberRight, 4);
            enPanel.add(numbersAppPS.getN63(), numberRight, 5);
            enPanel.add(numbersAppPS.getN64(), numberRight, 6);
            enPanel.add(numbersAppPS.getN65(), numberRight, 7);
            enPanel.add(numbersAppPS.getN66(), numberRight, 8);
            enPanel.add(numbersAppPS.getN67(), numberRight, 9);
            enPanel.add(numbersAppPS.getN68(), numberRight, 10);
            enPanel.add(numbersAppPS.getN69(), numberRight, 11);
            enPanel.add(numbersAppPS.getN70(), numberRight, 12);
            enPanel.add(numbersAppPS.getN71(), numberRight, 13);
            enPanel.add(numbersAppPS.getN72(), numberRight, 14);
            enPanel.add(numbersAppPS.getN73(), numberRight, 15);
            enPanel.add(numbersAppPS.getN74(), numberRight, 16);
            enPanel.add(numbersAppPS.getN75(), numberRight, 17);
            enPanel.add(numbersAppPS.getN76(), numberRight, 18);



            enPanel.add(labEn.getLabEn39(), textLeft, 0);
            enPanel.add(labEn.getLabEn40(), textLeft, 1);
            enPanel.add(labEn.getLabEn41(), textLeft, 2);
            enPanel.add(labEn.getLabEn42(), textLeft, 3);
            enPanel.add(labEn.getLabEn43(), textLeft, 4);
            enPanel.add(labEn.getLabEn44(), textLeft, 5);
            enPanel.add(labEn.getLabEn45(), textLeft, 6);
            enPanel.add(labEn.getLabEn46(), textLeft, 7);
            enPanel.add(labEn.getLabEn47(), textLeft, 8);
            enPanel.add(labEn.getLabEn48(), textLeft, 9);
            enPanel.add(labEn.getLabEn49(), textLeft, 10);
            enPanel.add(labEn.getLabEn50(), textLeft, 11);
            enPanel.add(labEn.getLabEn51(), textLeft, 12);
            enPanel.add(labEn.getLabEn52(), textLeft, 13);
            enPanel.add(labEn.getLabEn53(), textLeft, 14);
            enPanel.add(labEn.getLabEn54(), textLeft, 15);
            enPanel.add(labEn.getLabEn55(), textLeft, 16);
            enPanel.add(labEn.getLabEn56(), textLeft, 17);
            enPanel.add(labEn.getLabEn57(), textLeft, 18);
            enPanel.add(labEn.getLabEn58(), textRight, 0);
            enPanel.add(labEn.getLabEn59(), textRight, 1);
            enPanel.add(labEn.getLabEn60(), textRight, 2);
            enPanel.add(labEn.getLabEn61(), textRight, 3);
            enPanel.add(labEn.getLabEn62(), textRight, 4);
            enPanel.add(labEn.getLabEn63(), textRight, 5);
            enPanel.add(labEn.getLabEn64(), textRight, 6);
            enPanel.add(labEn.getLabEn65(), textRight, 7);
            enPanel.add(labEn.getLabEn66(), textRight, 8);
            enPanel.add(labEn.getLabEn67(), textRight, 9);
            enPanel.add(labEn.getLabEn68(), textRight, 10);
            enPanel.add(labEn.getLabEn69(), textRight, 11);
            enPanel.add(labEn.getLabEn70(), textRight, 12);
            enPanel.add(labEn.getLabEn71(), textRight, 13);
            enPanel.add(labEn.getLabEn72(), textRight, 14);
            enPanel.add(labEn.getLabEn73(), textRight, 15);
            enPanel.add(labEn.getLabEn74(), textRight, 16);
            enPanel.add(labEn.getLabEn75(), textRight, 17);
            enPanel.add(labEn.getLabEn76(), textRight, 18);

        } else if (str.byteValue() == 2){

            enPanel.add(numbersAppPS.getN77(), numberLeft, 0);
            enPanel.add(numbersAppPS.getN78(), numberLeft, 1);
            enPanel.add(numbersAppPS.getN79(), numberLeft, 2);
            enPanel.add(numbersAppPS.getN80(), numberLeft, 3);
            enPanel.add(numbersAppPS.getN81(), numberLeft, 4);
            enPanel.add(numbersAppPS.getN82(), numberLeft, 5);
            enPanel.add(numbersAppPS.getN83(), numberLeft, 6);
            enPanel.add(numbersAppPS.getN84(), numberLeft, 7);
            enPanel.add(numbersAppPS.getN85(), numberLeft, 8);
            enPanel.add(numbersAppPS.getN86(), numberLeft, 9);
            enPanel.add(numbersAppPS.getN87(), numberLeft, 10);
            enPanel.add(numbersAppPS.getN88(), numberLeft, 11);
            enPanel.add(numbersAppPS.getN89(), numberLeft, 12);
            enPanel.add(numbersAppPS.getN90(), numberLeft, 13);
            enPanel.add(numbersAppPS.getN91(), numberLeft, 14);
            enPanel.add(numbersAppPS.getN92(), numberLeft, 15);
            enPanel.add(numbersAppPS.getN93(), numberLeft, 16);
            enPanel.add(numbersAppPS.getN94(), numberLeft, 17);
            enPanel.add(numbersAppPS.getN95(), numberLeft, 18);
            enPanel.add(numbersAppPS.getN96(), numberRight, 0);
            enPanel.add(numbersAppPS.getN97(), numberRight, 1);
            enPanel.add(numbersAppPS.getN98(), numberRight, 2);
            enPanel.add(numbersAppPS.getN99(), numberRight, 3);
            enPanel.add(numbersAppPS.getN100(), numberRight, 4);
            enPanel.add(numbersAppPS.getN101(), numberRight, 5);
            enPanel.add(numbersAppPS.getN102(), numberRight, 6);
            enPanel.add(numbersAppPS.getN103(), numberRight, 7);
            enPanel.add(numbersAppPS.getN104(), numberRight, 8);
            enPanel.add(numbersAppPS.getN105(), numberRight, 9);
            enPanel.add(numbersAppPS.getN106(), numberRight, 10);
            enPanel.add(numbersAppPS.getN107(), numberRight, 11);
            enPanel.add(numbersAppPS.getN108(), numberRight, 12);
            enPanel.add(numbersAppPS.getN109(), numberRight, 13);
            enPanel.add(numbersAppPS.getN110(), numberRight, 14);
            enPanel.add(numbersAppPS.getN111(), numberRight, 15);
            enPanel.add(numbersAppPS.getN112(), numberRight, 16);
            enPanel.add(numbersAppPS.getN113(), numberRight, 17);
            enPanel.add(numbersAppPS.getN114(), numberRight, 18);

            enPanel.add(labEn.getLabEn77(), textLeft, 0);
            enPanel.add(labEn.getLabEn78(), textLeft, 1);
            enPanel.add(labEn.getLabEn79(), textLeft, 2);
            enPanel.add(labEn.getLabEn80(), textLeft, 3);
            enPanel.add(labEn.getLabEn81(), textLeft, 4);
            enPanel.add(labEn.getLabEn82(), textLeft, 5);
            enPanel.add(labEn.getLabEn83(), textLeft, 6);
            enPanel.add(labEn.getLabEn84(), textLeft, 7);
            enPanel.add(labEn.getLabEn85(), textLeft, 8);
            enPanel.add(labEn.getLabEn86(), textLeft, 9);
            enPanel.add(labEn.getLabEn87(), textLeft, 10);
            enPanel.add(labEn.getLabEn88(), textLeft, 11);
            enPanel.add(labEn.getLabEn89(), textLeft, 12);
            enPanel.add(labEn.getLabEn90(), textLeft, 13);
            enPanel.add(labEn.getLabEn91(), textLeft, 14);
            enPanel.add(labEn.getLabEn92(), textLeft, 15);
            enPanel.add(labEn.getLabEn93(), textLeft, 16);
            enPanel.add(labEn.getLabEn94(), textLeft, 17);
            enPanel.add(labEn.getLabEn95(), textLeft, 18);
            enPanel.add(labEn.getLabEn96(), textRight, 0);
            enPanel.add(labEn.getLabEn97(), textRight, 1);
            enPanel.add(labEn.getLabEn98(), textRight, 2);
            enPanel.add(labEn.getLabEn99(), textRight, 3);
            enPanel.add(labEn.getLabEn100(), textRight, 4);
            enPanel.add(labEn.getLabEn101(), textRight, 5);
            enPanel.add(labEn.getLabEn102(), textRight, 6);
            enPanel.add(labEn.getLabEn103(), textRight, 7);
            enPanel.add(labEn.getLabEn104(), textRight, 8);
            enPanel.add(labEn.getLabEn105(), textRight, 9);
            enPanel.add(labEn.getLabEn106(), textRight, 10);
            enPanel.add(labEn.getLabEn107(), textRight, 11);
            enPanel.add(labEn.getLabEn108(), textRight, 12);
            enPanel.add(labEn.getLabEn109(), textRight, 13);
            enPanel.add(labEn.getLabEn110(), textRight, 14);
            enPanel.add(labEn.getLabEn111(), textRight, 15);
            enPanel.add(labEn.getLabEn112(), textRight, 16);
            enPanel.add(labEn.getLabEn113(), textRight, 17);
            enPanel.add(labEn.getLabEn114(), textRight, 18);

        } else  if (str.byteValue() == 3){

            enPanel.add(numbersAppPS.getN115(), numberLeft, 0);
            enPanel.add(numbersAppPS.getN116(), numberLeft, 1);
            enPanel.add(numbersAppPS.getN117(), numberLeft, 2);
            enPanel.add(numbersAppPS.getN118(), numberLeft, 3);
            enPanel.add(numbersAppPS.getN119(), numberLeft, 4);
            enPanel.add(numbersAppPS.getN120(), numberLeft, 5);
            enPanel.add(numbersAppPS.getN121(), numberLeft, 6);
            enPanel.add(numbersAppPS.getN122(), numberLeft, 7);
            enPanel.add(numbersAppPS.getN123(), numberLeft, 8);
            enPanel.add(numbersAppPS.getN124(), numberLeft, 9);
            enPanel.add(numbersAppPS.getN125(), numberLeft, 10);
            enPanel.add(numbersAppPS.getN126(), numberLeft, 11);
            enPanel.add(numbersAppPS.getN127(), numberLeft, 12);
            enPanel.add(numbersAppPS.getN128(), numberLeft, 13);
            enPanel.add(numbersAppPS.getN129(), numberLeft, 14);
            enPanel.add(numbersAppPS.getN130(), numberLeft, 15);
            enPanel.add(numbersAppPS.getN131(), numberLeft, 16);
            enPanel.add(numbersAppPS.getN132(), numberLeft, 17);
            enPanel.add(numbersAppPS.getN133(), numberLeft, 18);
            enPanel.add(numbersAppPS.getN134(), numberRight, 0);
            enPanel.add(numbersAppPS.getN135(), numberRight, 1);
            enPanel.add(numbersAppPS.getN136(), numberRight, 2);
            enPanel.add(numbersAppPS.getN137(), numberRight, 3);
            enPanel.add(numbersAppPS.getN138(), numberRight, 4);
            enPanel.add(numbersAppPS.getN139(), numberRight, 5);
            enPanel.add(numbersAppPS.getN140(), numberRight, 6);
            enPanel.add(numbersAppPS.getN141(), numberRight, 7);
            enPanel.add(numbersAppPS.getN142(), numberRight, 8);
            enPanel.add(numbersAppPS.getN143(), numberRight, 9);
            enPanel.add(numbersAppPS.getN144(), numberRight, 10);
            enPanel.add(numbersAppPS.getN145(), numberRight, 11);
            enPanel.add(numbersAppPS.getN146(), numberRight, 12);
            enPanel.add(numbersAppPS.getN147(), numberRight, 13);
            enPanel.add(numbersAppPS.getN148(), numberRight, 14);
            enPanel.add(numbersAppPS.getN149(), numberRight, 15);
            enPanel.add(numbersAppPS.getN150(), numberRight, 16);
            enPanel.add(numbersAppPS.getN151(), numberRight, 17);
            enPanel.add(numbersAppPS.getN152(), numberRight, 18);

            enPanel.add(labEn.getLabEn115(), textLeft, 0);
            enPanel.add(labEn.getLabEn116(), textLeft, 1);
            enPanel.add(labEn.getLabEn117(), textLeft, 2);
            enPanel.add(labEn.getLabEn118(), textLeft, 3);
            enPanel.add(labEn.getLabEn119(), textLeft, 4);
            enPanel.add(labEn.getLabEn120(), textLeft, 5);
            enPanel.add(labEn.getLabEn121(), textLeft, 6);
            enPanel.add(labEn.getLabEn122(), textLeft, 7);
            enPanel.add(labEn.getLabEn123(), textLeft, 8);
            enPanel.add(labEn.getLabEn124(), textLeft, 9);
            enPanel.add(labEn.getLabEn125(), textLeft, 10);
            enPanel.add(labEn.getLabEn126(), textLeft, 11);
            enPanel.add(labEn.getLabEn127(), textLeft, 12);
            enPanel.add(labEn.getLabEn128(), textLeft, 13);
            enPanel.add(labEn.getLabEn129(), textLeft, 14);
            enPanel.add(labEn.getLabEn130(), textLeft, 15);
            enPanel.add(labEn.getLabEn131(), textLeft, 16);
            enPanel.add(labEn.getLabEn132(), textLeft, 17);
            enPanel.add(labEn.getLabEn133(), textLeft, 18);
            enPanel.add(labEn.getLabEn134(), textRight, 0);
            enPanel.add(labEn.getLabEn135(), textRight, 1);
            enPanel.add(labEn.getLabEn136(), textRight, 2);
            enPanel.add(labEn.getLabEn137(), textRight, 3);
            enPanel.add(labEn.getLabEn138(), textRight, 4);
            enPanel.add(labEn.getLabEn139(), textRight, 5);
            enPanel.add(labEn.getLabEn140(), textRight, 6);
            enPanel.add(labEn.getLabEn141(), textRight, 7);
            enPanel.add(labEn.getLabEn142(), textRight, 8);
            enPanel.add(labEn.getLabEn143(), textRight, 9);
            enPanel.add(labEn.getLabEn144(), textRight, 10);
            enPanel.add(labEn.getLabEn145(), textRight, 11);
            enPanel.add(labEn.getLabEn146(), textRight, 12);
            enPanel.add(labEn.getLabEn147(), textRight, 13);
            enPanel.add(labEn.getLabEn148(), textRight, 14);
            enPanel.add(labEn.getLabEn149(), textRight, 15);
            enPanel.add(labEn.getLabEn150(), textRight, 16);
            enPanel.add(labEn.getLabEn151(), textRight, 17);
            enPanel.add(labEn.getLabEn152(), textRight, 18);

        } else if (str.byteValue() == 4) {

            enPanel.add(numbersAppPS.getN153(), numberLeft, 0);
            enPanel.add(numbersAppPS.getN154(), numberLeft, 1);
            enPanel.add(numbersAppPS.getN155(), numberLeft, 2);
            enPanel.add(numbersAppPS.getN156(), numberLeft, 3);
            enPanel.add(numbersAppPS.getN157(), numberLeft, 4);
            enPanel.add(numbersAppPS.getN158(), numberLeft, 5);
            enPanel.add(numbersAppPS.getN159(), numberLeft, 6);
            enPanel.add(numbersAppPS.getN160(), numberLeft, 7);
            enPanel.add(numbersAppPS.getN161(), numberLeft, 8);
            enPanel.add(numbersAppPS.getN162(), numberLeft, 9);
            enPanel.add(numbersAppPS.getN163(), numberLeft, 10);
            enPanel.add(numbersAppPS.getN164(), numberLeft, 11);
            enPanel.add(numbersAppPS.getN165(), numberLeft, 12);
            enPanel.add(numbersAppPS.getN166(), numberLeft, 13);
            enPanel.add(numbersAppPS.getN167(), numberLeft, 14);
            enPanel.add(numbersAppPS.getN168(), numberLeft, 15);
            enPanel.add(numbersAppPS.getN169(), numberLeft, 16);
            enPanel.add(numbersAppPS.getN170(), numberLeft, 17);
            enPanel.add(numbersAppPS.getN171(), numberLeft, 18);
            enPanel.add(numbersAppPS.getN172(), numberRight, 0);
            enPanel.add(numbersAppPS.getN173(), numberRight, 1);
            enPanel.add(numbersAppPS.getN174(), numberRight, 2);
            enPanel.add(numbersAppPS.getN175(), numberRight, 3);
            enPanel.add(numbersAppPS.getN176(), numberRight, 4);
            enPanel.add(numbersAppPS.getN177(), numberRight, 5);
            enPanel.add(numbersAppPS.getN178(), numberRight, 6);
            enPanel.add(numbersAppPS.getN179(), numberRight, 7);
            enPanel.add(numbersAppPS.getN180(), numberRight, 8);
            enPanel.add(numbersAppPS.getN181(), numberRight, 9);
            enPanel.add(numbersAppPS.getN182(), numberRight, 10);
            enPanel.add(numbersAppPS.getN183(), numberRight, 11);
            enPanel.add(numbersAppPS.getN184(), numberRight, 12);
            enPanel.add(numbersAppPS.getN185(), numberRight, 13);
            enPanel.add(numbersAppPS.getN186(), numberRight, 14);
            enPanel.add(numbersAppPS.getN187(), numberRight, 15);
            enPanel.add(numbersAppPS.getN188(), numberRight, 16);
            enPanel.add(numbersAppPS.getN189(), numberRight, 17);
            enPanel.add(numbersAppPS.getN190(), numberRight, 18);

            enPanel.add(labEn.getLabEn153(), textLeft, 0);
            enPanel.add(labEn.getLabEn154(), textLeft, 1);
            enPanel.add(labEn.getLabEn155(), textLeft, 2);
            enPanel.add(labEn.getLabEn156(), textLeft, 3);
            enPanel.add(labEn.getLabEn157(), textLeft, 4);
            enPanel.add(labEn.getLabEn158(), textLeft, 5);
            enPanel.add(labEn.getLabEn159(), textLeft, 6);
            enPanel.add(labEn.getLabEn160(), textLeft, 7);
            enPanel.add(labEn.getLabEn161(), textLeft, 8);
            enPanel.add(labEn.getLabEn162(), textLeft, 9);
            enPanel.add(labEn.getLabEn163(), textLeft, 10);
            enPanel.add(labEn.getLabEn164(), textLeft, 11);
            enPanel.add(labEn.getLabEn165(), textLeft, 12);
            enPanel.add(labEn.getLabEn166(), textLeft, 13);
            enPanel.add(labEn.getLabEn167(), textLeft, 14);
            enPanel.add(labEn.getLabEn168(), textLeft, 15);
            enPanel.add(labEn.getLabEn169(), textLeft, 16);
            enPanel.add(labEn.getLabEn170(), textLeft, 17);
            enPanel.add(labEn.getLabEn171(), textLeft, 18);
            enPanel.add(labEn.getLabEn172(), textRight, 0);
            enPanel.add(labEn.getLabEn173(), textRight, 1);
            enPanel.add(labEn.getLabEn174(), textRight, 2);
            enPanel.add(labEn.getLabEn175(), textRight, 3);
            enPanel.add(labEn.getLabEn176(), textRight, 4);
            enPanel.add(labEn.getLabEn177(), textRight, 5);
            enPanel.add(labEn.getLabEn178(), textRight, 6);
            enPanel.add(labEn.getLabEn179(), textRight, 7);
            enPanel.add(labEn.getLabEn180(), textRight, 8);
            enPanel.add(labEn.getLabEn181(), textRight, 9);
            enPanel.add(labEn.getLabEn182(), textRight, 10);
            enPanel.add(labEn.getLabEn183(), textRight, 11);
            enPanel.add(labEn.getLabEn184(), textRight, 12);
            enPanel.add(labEn.getLabEn185(), textRight, 13);
            enPanel.add(labEn.getLabEn186(), textRight, 14);
            enPanel.add(labEn.getLabEn187(), textRight, 15);
            enPanel.add(labEn.getLabEn188(), textRight, 16);
            enPanel.add(labEn.getLabEn189(), textRight, 17);
            enPanel.add(labEn.getLabEn190(), textRight, 18);

        } else if (str.byteValue() == 5) {

            enPanel.add(numbersAppPS.getN191(), numberLeft, 0);
            enPanel.add(numbersAppPS.getN192(), numberLeft, 1);
            enPanel.add(numbersAppPS.getN193(), numberLeft, 2);
            enPanel.add(numbersAppPS.getN194(), numberLeft, 3);
            enPanel.add(numbersAppPS.getN195(), numberLeft, 4);
            enPanel.add(numbersAppPS.getN196(), numberLeft, 5);
            enPanel.add(numbersAppPS.getN197(), numberLeft, 6);
            enPanel.add(numbersAppPS.getN198(), numberLeft, 7);
            enPanel.add(numbersAppPS.getN199(), numberLeft, 8);
            enPanel.add(numbersAppPS.getN200(), numberLeft, 9);
            enPanel.add(numbersAppPS.getN201(), numberLeft, 10);
            enPanel.add(numbersAppPS.getN202(), numberLeft, 11);
            enPanel.add(numbersAppPS.getN203(), numberLeft, 12);
            enPanel.add(numbersAppPS.getN204(), numberLeft, 13);
            enPanel.add(numbersAppPS.getN205(), numberLeft, 14);
            enPanel.add(numbersAppPS.getN206(), numberLeft, 15);
            enPanel.add(numbersAppPS.getN207(), numberLeft, 16);
            enPanel.add(numbersAppPS.getN208(), numberLeft, 17);
            enPanel.add(numbersAppPS.getN209(), numberLeft, 18);
            enPanel.add(numbersAppPS.getN210(), numberRight, 0);
            enPanel.add(numbersAppPS.getN211(), numberRight, 1);
            enPanel.add(numbersAppPS.getN212(), numberRight, 2);
            enPanel.add(numbersAppPS.getN213(), numberRight, 3);
            enPanel.add(numbersAppPS.getN214(), numberRight, 4);
            enPanel.add(numbersAppPS.getN215(), numberRight, 5);
            enPanel.add(numbersAppPS.getN216(), numberRight, 6);
            enPanel.add(numbersAppPS.getN217(), numberRight, 7);
            enPanel.add(numbersAppPS.getN218(), numberRight, 8);
            enPanel.add(numbersAppPS.getN219(), numberRight, 9);
            enPanel.add(numbersAppPS.getN220(), numberRight, 10);
            enPanel.add(numbersAppPS.getN221(), numberRight, 11);
            enPanel.add(numbersAppPS.getN222(), numberRight, 12);
            enPanel.add(numbersAppPS.getN223(), numberRight, 13);
            enPanel.add(numbersAppPS.getN224(), numberRight, 14);
            enPanel.add(numbersAppPS.getN225(), numberRight, 15);
            enPanel.add(numbersAppPS.getN226(), numberRight, 16);
            enPanel.add(numbersAppPS.getN227(), numberRight, 17);
            enPanel.add(numbersAppPS.getN228(), numberRight, 18);

            enPanel.add(labEn.getLabEn191(), textLeft, 0);
            enPanel.add(labEn.getLabEn192(), textLeft, 1);
            enPanel.add(labEn.getLabEn193(), textLeft, 2);
            enPanel.add(labEn.getLabEn194(), textLeft, 3);
            enPanel.add(labEn.getLabEn195(), textLeft, 4);
            enPanel.add(labEn.getLabEn196(), textLeft, 5);
            enPanel.add(labEn.getLabEn197(), textLeft, 6);
            enPanel.add(labEn.getLabEn198(), textLeft, 7);
            enPanel.add(labEn.getLabEn199(), textLeft, 8);
            enPanel.add(labEn.getLabEn200(), textLeft, 9);
            enPanel.add(labEn.getLabEn201(), textLeft, 10);
            enPanel.add(labEn.getLabEn202(), textLeft, 11);
            enPanel.add(labEn.getLabEn203(), textLeft, 12);
            enPanel.add(labEn.getLabEn204(), textLeft, 13);
            enPanel.add(labEn.getLabEn205(), textLeft, 14);
            enPanel.add(labEn.getLabEn206(), textLeft, 15);
            enPanel.add(labEn.getLabEn207(), textLeft, 16);
            enPanel.add(labEn.getLabEn208(), textLeft, 17);
            enPanel.add(labEn.getLabEn209(), textLeft, 18);
            enPanel.add(labEn.getLabEn210(), textRight, 0);
            enPanel.add(labEn.getLabEn211(), textRight, 1);
            enPanel.add(labEn.getLabEn212(), textRight, 2);
            enPanel.add(labEn.getLabEn213(), textRight, 3);
            enPanel.add(labEn.getLabEn214(), textRight, 4);
            enPanel.add(labEn.getLabEn215(), textRight, 5);
            enPanel.add(labEn.getLabEn216(), textRight, 6);
            enPanel.add(labEn.getLabEn217(), textRight, 7);
            enPanel.add(labEn.getLabEn218(), textRight, 8);
            enPanel.add(labEn.getLabEn219(), textRight, 9);
            enPanel.add(labEn.getLabEn220(), textRight, 10);
            enPanel.add(labEn.getLabEn221(), textRight, 11);
            enPanel.add(labEn.getLabEn222(), textRight, 12);
            enPanel.add(labEn.getLabEn223(), textRight, 13);
            enPanel.add(labEn.getLabEn224(), textRight, 14);
            enPanel.add(labEn.getLabEn225(), textRight, 15);
            enPanel.add(labEn.getLabEn226(), textRight, 16);
            enPanel.add(labEn.getLabEn227(), textRight, 17);
            enPanel.add(labEn.getLabEn228(), textRight, 18);

        }  else if (str.byteValue() == 6) {

            enPanel.add(numbersAppPS.getN229(), numberLeft, 0);
            enPanel.add(numbersAppPS.getN230(), numberLeft, 1);
            enPanel.add(numbersAppPS.getN231(), numberLeft, 2);
            enPanel.add(numbersAppPS.getN232(), numberLeft, 3);
            enPanel.add(numbersAppPS.getN233(), numberLeft, 4);
            enPanel.add(numbersAppPS.getN234(), numberLeft, 5);
            enPanel.add(numbersAppPS.getN235(), numberRight, 0);
            enPanel.add(numbersAppPS.getN236(), numberRight, 1);
            enPanel.add(numbersAppPS.getN237(), numberRight, 2);
            enPanel.add(numbersAppPS.getN238(), numberRight, 3);
            enPanel.add(numbersAppPS.getN239(), numberRight, 4);
            enPanel.add(numbersAppPS.getN240(), numberRight, 5);

            enPanel.add(labEn.getLabEn229(), textLeft, 0);
            enPanel.add(labEn.getLabEn230(), textLeft, 1);
            enPanel.add(labEn.getLabEn231(), textLeft, 2);
            enPanel.add(labEn.getLabEn232(), textLeft, 3);
            enPanel.add(labEn.getLabEn233(), textLeft, 4);
            enPanel.add(labEn.getLabEn234(), textLeft, 5);
            enPanel.add(labEn.getLabEn235(), textRight, 0);
            enPanel.add(labEn.getLabEn236(), textRight, 1);
            enPanel.add(labEn.getLabEn237(), textRight, 2);
            enPanel.add(labEn.getLabEn238(), textRight, 3);
            enPanel.add(labEn.getLabEn239(), textRight, 4);
            enPanel.add(labEn.getLabEn240(), textRight, 5);

        }
        return enPanel;
    }

}
